[assets.production]
name = "Discover"
model = "StudioDiscover.rbxm"
environment = "production"
description = "Browse and install Wally packages without leaving Roblox Studio."
type = "Package"

[environments.production]
creatorId = 48044582
creatorType = "User"
universeId = 10052915661
placeId = 136229012533810
