// Augments the Env generated by `wrangler types`. After regenerating,
// this declaration is merged with Cloudflare.Env and is harmless to keep.
declare global {
	namespace Cloudflare {
		interface Env {
			RATE_LIMITER: RateLimit;
		}
	}
}

export type HonoEnv = {
	Bindings: Env;
	Variables: {
		uid: string;
		version: string;
	};
};
