return {
	{
		scope = "evaera",
		name = "cmdr",
		description = "Extensible command console for Roblox developers",
		realm = "shared",
	},
	{
		scope = "jsdotlua",
		name = "react",
		description = "A comprehensive, but not exhaustive, translation of ReactJS 17.x into Luau.",
		realm = "shared",
	},
	{ scope = "evaera", name = "promise", description = "Promise implementation for Roblox", realm = "shared" },
	{ scope = "jsdotlua", name = "jest", description = "Delightful testing for Luau.", realm = "shared" },
	{ scope = "sleitnick", name = "knit", description = "Knit is a lightweight game framework", realm = "shared" },
	{
		scope = "howmanysmall",
		name = "janitor",
		description = "A garbage collector object implementation for Roblox, featuring support for custom cleanup methods, Promises, and instance linking.",
		realm = "shared",
	},
}
