name: Lint

on:
  push:
    branches: [main]
    paths:
      - "**/*.lua"
      - "**/*.luau"
      - "stylua.toml"
      - "selene.toml"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**/*.lua"
      - "**/*.luau"
      - "stylua.toml"
      - "selene.toml"
      - ".github/workflows/lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Install packages
        run: lune run install --quiet

      - name: 🎨 StyLua check
        run: stylua --check plugin/bin plugin/src

      - name: 🔍 Selene
        run: selene plugin/bin plugin/src
